export type Platform = "codex" | "claude"

export const PROTOCOL_CONSUMER_SKILLS = ["cvg-build-loop", "cvg-plan-loop"] as const

const MARKER_RE = /^<!-- (\/?)(codex|claude) -->$/

// Strips `<!-- codex -->` / `<!-- claude -->` line-marker blocks from skill
// markdown: blocks for the target platform keep their content (markers
// removed), blocks for the other platform are removed entirely. Marker lines
// must stand alone on their own line; nesting is not supported.
export function stripPlatform(content: string, platform: Platform): string {
  const kept: string[] = []
  let open: Platform | null = null

  content.split("\n").forEach((line, index) => {
    const marker = line.trim().match(MARKER_RE)
    if (!marker) {
      if (open === null || open === platform) {
        kept.push(line)
      }
      return
    }

    const closing = marker[1] === "/"
    const name = marker[2] as Platform
    if (closing) {
      if (open !== name) {
        throw new Error(`line ${index + 1}: closing marker <!-- /${name} --> without matching <!-- ${name} -->`)
      }
      open = null
    } else {
      if (open !== null) {
        throw new Error(`line ${index + 1}: nested platform marker <!-- ${name} --> inside <!-- ${open} -->`)
      }
      open = name
    }
  })

  if (open !== null) {
    throw new Error(`unclosed platform marker <!-- ${open} -->`)
  }

  return kept.join("\n").replace(/\n{3,}/g, "\n\n")
}

export function assertNoPlatformMarkers(content: string, label: string): void {
  for (const line of content.split("\n")) {
    if (MARKER_RE.test(line.trim())) {
      throw new Error(`${label}: unexpected platform marker in platform-neutral content: ${line.trim()}`)
    }
  }
}

// Renders the skill-local protocol copy that keeps a loop skill self-contained
// when installed from a marketplace cache. The canonical text lives only in
// skills-src/cvg-multi-session/SKILL.md; platform markers are preserved so the
// caller can strip the result per platform.
export function renderProtocolReference(multiSessionSkill: string, forSkill: string): string {
  const body = multiSessionSkill.replace(/^---\n[\s\S]*?\n---\n+/, "")
  const title = "# Multi-Session Workflow"
  if (!body.startsWith(title)) {
    throw new Error(`cvg-multi-session/SKILL.md must start with "${title}" after frontmatter`)
  }

  const rest = body.slice(title.length).replace(/^\n+/, "").replace("Use this skill when", "Use this protocol when")

  return [
    "# Multi-Session Protocol Reference",
    "",
    `This file is a skill-local copy of the \`cvg-multi-session\` protocol needed by \`${forSkill}\`. It keeps the loop skill self-contained when installed from a marketplace cache. Generated by \`bun run sync\` from \`skills-src/cvg-multi-session/SKILL.md\`; do not edit by hand.`,
    "",
    rest,
  ].join("\n")
}
